# SITE CONFIGURATION
title: Combinatorics in Christchurch # your site title
author: 
#description: > # Meta description of Homepage
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://combinatoricsinchristchurch.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Combinatorics in Christchurch', link: '/'}
  - {name: 'Registration and Abstract Submission', link: '/registration'}
  - {name: 'Local Information', link: '/localinfo'}
  - {name: 'Programme', link: '/programme'}
  - {name: 'Participants', link: '/participants'}

#tagline: >
#  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: GodleyHead.JPG # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
